---
name: Deploy Development Image to registry

on:
  push:
    branches:
      - ci/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Image
      run: |
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        TAG=$(echo "$GIT_BRANCH" | cut -d "/" -f2)
        docker login ${{ secrets.REGISTRY_ENDPOINT }} -u userdoesnotmatter -p ${{ secrets.TOKEN }}
        docker build . --compress --tag $TAG
        docker push "${{ secrets.REGISTRY_ENDPOINT }}/${{ secrets.REGISTRY_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:$TAG"
    - name: Deploy container
      run: |
        CONTAINER_ID=$(sed -e 's/^"//' -e 's/"$//' <<<$(curl -X GET -H "X-Auth-Token: ${{ secrets.TOKEN}}" "https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/" | jq -e '.containers[] | select(.name|test("${{ secrets.NAME }}"))'.id))
        curl \
          -X POST \
          -H "X-Auth-Token: ${{ secrets.TOKEN }}" \
          -d "{}" \
          "https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/$CONTAINER_ID/deploy" \
          | jq 'del(."environment_variables")'
    - name: Retrieve tag name
      run: |

